spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.1.8.83:3306/operator?useSSL=false
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: master
